### ISSUE TITLE
[Docs]: Luck of information about env_vars

### ISSUE THREAD

**Issue by mi4i0** [semaphoreci/semaphore#311]
### Type

New content idea

### What do you want to report?

In previous version of SemaphoreCI doc was provided more information about vars and examples of their usage. Current version provides only the basics of basic
Example: [what i found](https://docs.semaphoreci.com/reference/pipeline-yaml#env-vars-in-jobs)
```
env_vars:
          - name: VAR_1
            value: This is VAR_1
          - name: VAR_2
            value: This is VAR_2
```

But actually no information that could be required or optional, could have arrays of values, could have default value, etc.
```
      env_vars:
        - required: true
          options:
            - 'Option 1' 
            - 'Option 2'
          default_value: 'default value'
          name: SOME_NAME
```
Could you provide more examples?

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/semaphoreci/semaphore?tab=coc-ov-file)
