### ISSUE TITLE
Auto promote on tags

### ISSUE THREAD

**Issue by rbngzlv** [semaphoreci/semaphore#35]
Hi, would be nice if we can use tags to auto promote pipelines, for example:

We will deploy all master commits to the staging environment, and only the tagged commits to the production environment:

```yml
promotions:
- name: Build staging containers
  pipeline_file: staging-build.yml
  auto_promote_on:
    - result: passed
      branch:
        - "^master$"

- name: Build production containers
  pipeline_file: production-build.yml
  auto_promote_on:
    - result: passed
      branch:
        - "^master$"
      tag: # New rule to add to sempahoreci
        - "^v((?!rc).)*$"
```

But, I'm not sure if sempahoreci runs when a tag is created.

Now, I'm always auto promoting the `build` pipeline on `master` branch and tagging the docker image as `staging` or  with the git tag if the commit is tagged, but for other cases can be util.

**Comment by rbngzlv** [comment]
Forget this, I can auto promote on tags using:

```yml
promotions:
  - name: Deploy to staging
    pipeline_file: staging-deploy.yml
    auto_promote_on:
      - result: passed
        branch:
          - ^refs/tags/v.*rc\d+$
```
