### ISSUE TITLE
Parameterized Builds

### ISSUE THREAD

**Issue by n3ziniuka5** [semaphoreci/semaphore#46]
Jenkins allows to specify parameters required to start the pipeline:
```groovy
pipeline {
    agent any
    parameters {
        string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')

        text(name: 'BIOGRAPHY', defaultValue: '', description: 'Enter some information about the person')

        booleanParam(name: 'TOGGLE', defaultValue: true, description: 'Toggle this value')

        choice(name: 'CHOICE', choices: ['One', 'Two', 'Three'], description: 'Pick something')

        password(name: 'PASSWORD', defaultValue: 'SECRET', description: 'Enter a password')
    }
    stages {
        stage('Example') {
            steps {
                echo "Hello ${params.PERSON}"

                echo "Biography: ${params.BIOGRAPHY}"

                echo "Toggle: ${params.TOGGLE}"

                echo "Choice: ${params.CHOICE}"

                echo "Password: ${params.PASSWORD}"
            }
        }
    }
}
```

This would be very useful in SemaphoreCI promotions. You could have a `deploy.yml` pipeline that would accept certain parameters, like deployment target, image version, etc. Then when calling that pipeline you would do:
```yml
promotions:
  - name: Deploy
    pipeline_file: deploy.yml
    parameters:
      - name: version
         value: 1.0.0
      - name: target
         value: staging
```

**Comment by rastasheep** [comment]
I'm having very similar situation/use-case.
My whole setup is contained of three pipelines, testing, build, promote.
When tests pass we build docker image (artifact), and after that we promote newly created image to desired environment.
Since organize our code in mono-repo, first pipeline (test phase) is shared between multiple services, but build and promote pipelines are defined for every service for every environment. So at the end of the day, our CI setup in spread between 70 yml files.

The real difference between environment promote pipelines for one service is just which "secrete" we use for execution. For example we have following:
`serviceA-build.yml`
```

version: v1.0
name: Build serviceA
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
blocks:
...

promotions:
  - name: Promote production
    pipeline_file: serviceA-promote-production.yml

  - name: Promote staging
    pipeline_file: serviceA-promote-staging.yml
...

```
And for promotion:
`serviceA-promote-production.yml`
```
version: v1.0
name: Promote serviceA production
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
blocks:
  - name: Promote
    task:
      secrets:
        - name: aws-secrets
        - name: serviceA-promote-production
      jobs:
        - name: 'ecs update'
          commands:
            - checkout
            - ./services/service-a/script/promote
```
`serviceA-promote-staging.yml`
```
version: v1.0
name: Promote serviceA staging
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
blocks:
  - name: Promote
    task:
      secrets:
        - name: aws-secrets
        - name: serviceA-promote-staging
      jobs:
        - name: 'ecs update'
          commands:
            - checkout
            - ./services/service-a/script/promote
```
and so on.

It would be great to have something like:
serviceA-build.yml
```

version: v1.0
name: Build serviceA
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
blocks:
...

promotions:
  - name: Promote production
    pipeline_file: serviceA-promote.yml
    secrets:
        - name: serviceA-promote-production
    parameters:
      - name: stage
         value: production

  - name: Promote staging
    pipeline_file: serviceA-promote.yml
    secrets:
        - name: serviceA-promote-staging
    parameters:
        - name: stage
          value: staging
...

```
And for promotion:
`serviceA-promote.yml`
```
version: v1.0
name: Promote serviceA  ${params.STAGE}
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
blocks:
  - name: Promote
    task:
      secrets:
        - name: aws-secrets
        - name: ${params.SECRET} // maybe even this?
      jobs:
        - name: 'ecs update'
          commands:
            - checkout
            - ./services/service-a/script/promote
```

Any thoughts?
