### ISSUE TITLE
Dependent Builds

### ISSUE THREAD

**Issue by n3ziniuka5** [semaphoreci/semaphore#47]
It would be great if projects could depend on each other. One use-case would be a dedicated repository for end-to-end tests and we want to trigger those tests when other projects are updated.

Currently we could use the cli tool to manually invoke the pipeline, but that would mean having it in every upstream project, which is a hassle to maintain. And if you need to change something it may require changing again every upstream project.

Jenkins allows you to trigger a pipeline when an upstream pipeline finishes:
```groovy
triggers { 
  upstream(upstreamProjects: 'job1,job2', threshold: hudson.model.Result.SUCCESS)
}
```

It would be great to be able to define something similar in Semaphore CI:

```yml
spec:
  repository:
    url: "git@github.com:renderedtext/goDemo.git"
    run: true
    run_on:
      - branches
      - tags
  schedulers:
    - name: first-scheduler
      branch: master
      at: "5 4 * * *"
      pipeline_file: ".semaphore/cron.yml"
    - name: second-scheduler
      branch: master
      at: "5 3 * * *"
      pipeline_file: ".semaphore/semaphore.yml"
  upstream:
    - project: upstream-project
      result: any
      branch: "*"
      pipeline_file: ".semaphore/end-to-end-tests.yml"
    - project: upstream-project-2
      result: passed
      branch: master
      pipeline_file: ".semaphore/end-to-end-tests.yml"
```
