### ISSUE TITLE
Allow YAML anchors

### ISSUE THREAD

**Issue by devxpy** [semaphoreci/semaphore#51]
Please allow using [YAML Anchors](https://blog.daemonl.com/2016/02/yaml.html).

They are really useful in re-using blocks of config!

For e.g.

```yaml
blocks:
  - name: Task1
    task:
      prologue:
        &prologue-commands
        commands:
           - checkout

  - name: Task2
     task:
       prologue:
          <<: *prologue-commands
            
```

I get this error:
![image](https://user-images.githubusercontent.com/19492893/63410937-055dce80-c412-11e9-8ef1-c4a72cea3543.png)
