### ISSUE TITLE
change_not_in for conditions

### ISSUE THREAD

**Issue by romanlex** [semaphoreci/semaphore#63]
Hello.
In semaphore pipeline I can use [change_in ](https://docs.semaphoreci.com/reference/conditions-reference/#change_in) function.
For example, I have monorepo with structure:

```
.
├── Brewfile
├── Capfile
├── Gemfile
├── Gemfile.lock
├── Procfile
├── Procfile.static
├── README.md
├── Rakefile
├── app
├── bin
├── client
├── config
├── db
├── doc
├── docker-compose.yml.sample
├── engines
├── lib
├── log
├── package-lock.json
├── package.json
├── public
├── spec
└── tmp
```

Frontend: all files from `client` directory
Backend: all other files

In pipeline I have this block for Client section:
```
blocks:
  - name: "Client: install dependencies"
    dependencies: []
    run:
      when: "change_in(['/client', '/public'])"
```

If the client part is not touched CI skip these blocks.
I want to skip backend jobs if any other files without client or public dir were changed.

**Comment by shiroyasha** [comment]
@romanlex thanks for opening this feature request.

We have the following expression that you can use in your pipeline:

``` yaml
blocks:
  - name: "Backend Tests"
    run:
      when: "change_in(['/client', '/public']) = false"
```

Would this work for your project?

---

At the moment, we are re-implementing the change_in evaluator, making it faster and more stable along the way.
If you have any other things that would be useful for your project, please let us know. 
Now is the perfect time to introduce new functionality. 

The new change_in evaluator is open-source and the progress can be tracked in this repository
—> https://github.com/semaphoreci/spc
—> https://github.com/semaphoreci/spc/tree/master/test/e2e
