### ISSUE TITLE
Run job conditionally

### ISSUE THREAD

**Issue by aprilmintacpineda** [semaphoreci/semaphore#64]
I want to be able to divide my CD flow into mulitple jobs and then conditionally run a job using `jobs[n].when` like with `blocks.run.when`

```yaml
blocks:
  - name: Development
    run:
      when: branch = 'dev'
    task:
      secrets:
        - name: Dev Variables
      jobs:
        - name: Initialize
          commands:
            - checkout
        - name: DB Migration
          when: changeIn(['/migrations', '/.migrate.config.json']) # <---- this part
          commands:
            - yarn db:migrate
        - name: Install deps
          commands:
            - yarn
            - bundle
        - name: Build
          commands:
            - yarn build
```
