### ISSUE TITLE
Promotion on .yml artifact

### ISSUE THREAD

**Issue by JuRoy** [semaphoreci/semaphore#65]
Is it possible to start a promotion on dynamically generated file stored in an artifact?

We need this feature since we are in monorepo and the `matrix` feature is not flexible enough

Gitlab equivalent:
```
  trigger:
    include:
      - artifact: generated-config.yml
        job: jsonnet
```
